config/routes.rb
InlieuLaunch::Application.routes.draw do
  
  resources :users, :only => [:create, :show]

  namespace :admin do
    resources :users, :except => :create
  end

  root to: 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :event, :inlieu, :name
  before_save { |user| user.email = email.downcase }

  validates(:name, presence: true, length: {maximum: 50} )
  validates(:event, presence: true, length: {maximum: 50} )
  validates(:inlieu, presence: true, length: {maximum: 50} )
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:true, format: { with: VALID_EMAIL_REGEX },
  					uniqueness: { case_sensitive: false}
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate
  
  def index
    @users = User.all
  end

  def edit

  end

  def show
    @user = User.find(params[:id])
  end

  def update

  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to @user
  end

  protected

  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['HTTP_USER'] && password == ENV['HTTP_PASS']
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(params[:user])
  	if @user.save
  		redirect_to "http://inlieugiving.com/join"
  	else
  		render 'new'
  	end
  end
  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<h1> Users Index </h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Event</th>
    <th>Inlieu</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
	<td> <%= user.name %> </td>
	<td> <%= user.email %> </td>
  <td> <%= user.event %> </td>
  <td> <%= user.inlieu %> </td>
	<td> <%= link_to 'Show', admin_users_path + "/" +user.id.to_s() %> </td>
	<td> <%= link_to 'Destroy', admin_users_path + "/" +user.id.to_s(), html_options = {:method => :delete} %> </td>
  </tr>
<% end %>

</table>

app/views/admin/users/new.html.erb
<h1>Inlieu Giving</h1>

<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :Name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label "Name your event" %>
      <%= f.text_field :event %>

	  <%= f.label "Inlieu of what? ex: Birthday, wedding, etc" %>
      <%= f.text_field :inlieu %>
      
      <%= f.submit "Go create my campaign", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @user.name %>
      </h1>
      <h1>
        <%= @user.email %>
      </h1>
      <h1>
        <%= @user.event %>
      </h1>
      <h1>
        <%= @user.inlieu %>
      </h1>
    </section>
  </aside>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Ugly InLieu
  </small>
  <nav>
    <ul>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Ugly InLieu", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inlieu</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
  <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/index.html.erb
<h1> Users Index </h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Event</th>
    <th>Inlieu</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
	<td> <%= user.name %> </td>
	<td> <%= user.email %> </td>
  <td> <%= user.event %> </td>
  <td> <%= user.inlieu %> </td>
	<td> <%= link_to 'Show', user %> </td>
	<td> <%= link_to 'Destroy', user, html_options = {:method => :delete} %> </td>
  </tr>
<% end %>

</table>